name: eight-pop

defaults:
  locator_prefix: fc00:0::/32
  link_prefix: fc00:1::/32
  host_prefix: fd00::/48

pops:
  - id: A
  - id: B
  - id: C
  - id: D
  - id: E
  - id: F
  - id: G
  - id: H

hosts:
  - id: hA
    attach: A

  - id: hC
    attach: C

links:
  - [A,B,2]
  - [A,D,2]
  - [B,C,2]
  - [B,D]
  - [C,E,3]
  - [C,F,2]
  - [D,E]
  - [E,F]
  - [F,G,2]
  - [F,H]
  - [G,H]
