frr version 10.5.1
frr defaults traditional
hostname popB
log stdout
service integrated-vtysh-config
!
interface lo
 ipv6 address fc00:0:2::1/48
 ipv6 router isis CORE
 isis passive
!
interface eth1
 description core link to popA
 ipv6 router isis CORE
 isis network point-to-point
!
interface eth2
 description core link to popC
 ipv6 router isis CORE
 isis network point-to-point
!
router isis CORE
 net 49.0000.0000.0000.0002.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
!
