stages:
  - lint
  - test

editorconfig:
  stage: lint
  image:
    name: mstruebing/editorconfig-checker:latest
    entrypoint: [""]
  script:
    - editorconfig-checker

lint:
  image: golangci/golangci-lint:latest
  stage: lint
  cache:
    key: golangci-lint-$CI_COMMIT_REF_SLUG
    paths:
      - .cache/golangci-lint
      - .cache/go/pkg/mod
  variables:
    GOLANGCI_LINT_CACHE: $CI_PROJECT_DIR/.cache/golangci-lint
    GOPATH: $CI_PROJECT_DIR/.cache/go
  script:
    - make lint

test.unit:
  stage: test
  script:
    - make test.unit

test.integration:
  stage: test
  script:
    - make test.integration
