# Docker compose file typicall used for dev-only containers
# Example: sqlc generations, protobuf generators etc.

services:
  sqlc:
    image: sqlc/sqlc:latest
    container_name: maeto-dev-sqlc
    volumes:
      - .:/src
    working_dir: /src
    command: generate
    user: "${UID}:${GID}"

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: maeto-nats-nui
    ports:
      - "31311:31311"
    volumes:
      - nats-nui-db:/db
    networks:
      - default
      - clab

networks:
  clab:
    external: true

volumes:
  nats-nui-db:
