services:
  db:
      image: timescale/timescaledb:latest-pg17
      container_name: maeto-timescaledb
      environment:
        - POSTGRES_PASSWORD=admin
      volumes:
        - ./db/init/:/docker-entrypoint-initdb.d/
      ports:
        - 5435:5432

  nats-server:
    image: nats:2.12.7-scratch
    container_name: cepheus-nats
    ports:
      - 4222:4222
      - 8222:8222
    command: ["--http_port", "8222", "-js", "-sd", "/data"]

  maeto-argus:
    image: maeto-argus:latest
    container_name: maeto-argus
    build:
      context: .
      dockerfile: docker/maeto-argus.Dockerfile
    ports:
      - 8087:8080
    environment:
      - OTEL_SINK=otel
      - OTEL_ENDPOINT=otel-collector:4318
      - DETECTION_INTERVAL_SECONDS=10
      - maeto_DB_URL=postgres://postgres:admin@db:5432/postgres?sslmode=disable
      - NATS_CONNECT_URL=nats://nats-server:4222
    depends_on:
      - db
      - nats-server
