services:
  stamp-suite-reflector:
    image: test-stamp-suite:latest
    container_name: maeto-test-reflector-stamp-suite
    ports:
      - "862:862/udp"
    command: "./target/release/stamp-suite -i"
