# Docker compose file typicall used for dev-only containers
# Example: sqlc generations, protobuf generators etc.

services:
  sqlc:
    image: sqlc/sqlc:latest
    container_name: maeto-dev-sqlc
    volumes:
      - .:/src
    working_dir: /src
    command: generate
    user: "${UID}:${GID}"
