---
- name: Provision containerlab host
  hosts: all
  become: true
  vars:
    docker_users:
      - vagrant
    docker_install_compose_plugin: true

  roles:
    - geerlingguy.docker

  tasks:
    - name: Copy version.env
      ansible.builtin.copy:
        src: version.env
        dest: /tmp/version.env
        mode: "0644"

    - name: Load a value from version.env
      ansible.builtin.set_fact:
        containerlab_version: "{{ lookup('ansible.builtin.ini', 'CONTAINERLAB_VERSION type=properties file=version.env') }}"

    - name: Install base deps
      ansible.builtin.apt:
        name:
          - traceroute
          - iputils-ping
          - net-tools
          - tcpdump
          - iperf3
          - dnsutils
          - iproute2
          - curl
          - mtr-tiny
          - jq
          - gnupg
          - lsb-release
          - "linux-modules-extra-{{ ansible_kernel }}"
          - make
          - strongswan
          - strongswan-pki
          - libcharon-extra-plugins
          - libcharon-extauth-plugins
          - libstrongswan-extra-plugins
          - libtss2-tcti-tabrmd0 # https://stackoverflow.com/a/70720567
        state: present
        update_cache: true

    - name: Load dataplane modules now
      ansible.builtin.command: "modprobe {{ item }}"
      changed_when: false
      loop:
        - vrf
        - xfrm_interface
        - esp6

    - name: Load dataplane modules on boot
      ansible.builtin.copy:
        content: "vrf\nxfrm_interface\nesp6\n"
        dest: /etc/modules-load.d/maeto.conf
        mode: "0644"

    - name: Install containerlab
      ansible.builtin.shell: >-
        bash -c "$(curl -sL https://get.containerlab.dev)" --
        -v {{ containerlab_version }}
      args:
        creates: /usr/bin/containerlab
