frr version 10.5.1
frr defaults traditional
hostname popA
log stdout
service integrated-vtysh-config
!
interface lo
 ipv6 address fc00:0:1::1/128
 ipv6 router isis CORE
 isis passive
!
interface eth1
 description core link to popB
 ipv6 address fc00:1:0:1::1/64
 ipv6 router isis CORE
 isis network point-to-point
!
interface eth2
 description core link to popD
 ipv6 address fc00:1:0:2::1/64
 ipv6 router isis CORE
 isis network point-to-point
!
ipv6 route fc00:0:1::/48 blackhole
!
router isis CORE
 net 49.0000.0000.0000.0001.00
 is-type level-1
 metric-style wide
 topology ipv6-unicast
 redistribute ipv6 static level-1
!
